### ISSUE TITLE
Notes regarding other repos

### ISSUE THREAD

**Issue by DonaldTsang** [wenbihan/reproducible-image-denoising-state-of-the-art#10]
See https://github.com/flyywh/Image-Denoising-State-of-the-art which has less info...
Might want to take notes about that.

**Comment by DonaldTsang** [comment]
Also https://github.com/z-bingo/awesome-image-denoising-state-of-the-art

**Comment by wenbihan** [comment]
Good point. Comparing to https://github.com/flyywh/Image-Denoising-State-of-the-art, this repo only includes those works with reproducible codes / implementations.
